# Generated by Django 2.2.9 on 2020-01-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedDirs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Directories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('backup_type', models.CharField(max_length=50)),
                ('remote_user', models.CharField(max_length=200)),
                ('remote_pass', models.CharField(max_length=200)),
                ('exclude_dirs', models.ManyToManyField(to='webinterface.ExcludedDirs')),
            ],
        ),
    ]
