# Generated by Django 2.2.9 on 2020-01-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='directories',
            name='path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='directories',
            name='remote_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='directories',
            name='backup_type',
            field=models.CharField(default='folder', max_length=50),
        ),
        migrations.AlterField(
            model_name='directories',
            name='location',
            field=models.CharField(default='local', max_length=50),
        ),
        migrations.AlterField(
            model_name='directories',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='directories',
            name='remote_pass',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='directories',
            name='remote_user',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='excludeddirs',
            name='directory',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_hour', models.IntegerField(default=4)),
                ('tmp_dir', models.CharField(default='./', max_length=200)),
                ('encrypt_pass', models.CharField(default='1234', max_length=100)),
                ('notification', models.ManyToManyField(to='webinterface.Notification')),
            ],
        ),
    ]
