# Generated by Django 2.2.9 on 2020-01-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0002_auto_20200114_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_date', models.DateTimeField(verbose_name='Created date')),
                ('path', models.CharField(default='', max_length=200)),
                ('size', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='directories',
            name='exclude_dirs',
            field=models.ManyToManyField(blank=True, to='webinterface.ExcludedDirs'),
        ),
        migrations.AlterField(
            model_name='directories',
            name='remote_pass',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='directories',
            name='remote_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='directories',
            name='remote_user',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
