# Generated by Django 2.2.9 on 2020-01-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0003_auto_20200114_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('message', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
